DESC customer_details
SELECT CNO FROM CUSTOMER_DETAILS;
SELECT CNO,CNAME FROM CUSTOMER_dETAILS;
DESC customer_details
SELECT CNO CUSTOMER ,ADDRESS,GENDER G FROM CUSTOMER_DETAILS;
SELECT * FROM customer_details;
SELECT DISTINCT(CNO) FROM customer_details;
SELECT CNO,ADDRESS FROM customer_details ORDER BY CNO,ADDRESS DESC;
SELECT CNO FROM customer_details;